id: P6DD67A47
initial_creation_type: ocr
source_metadata:
  volumes:
    ec587fb57e144b0d99315bd793c22ab6:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཕགས་པ་ཡི་གེ་དྲུག་པའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      volume_number: 37
